In [4]:
import numpy as np
import pandas as pd
train=pd.read_csv(r"C:\Users\sairam\Downloads\flight-delays-fall-2018\flight_delays_train.csv")
test=pd.read_csv(r"C:\Users\sairam\Downloads\flight-delays-fall-2018\flight_delays_test.csv")
data.head()

Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance  \
0   c-8       c-21       c-7     1934            AA    ATL  DFW       732   
1   c-4       c-20       c-3     1548            US    PIT  MCO       834   
2   c-9        c-2       c-5     1422            XE    RDU  CLE       416   
3  c-11       c-25       c-6     1015            OO    DEN  MEM       872   
4  c-10        c-7       c-6     1828            WN    MDW  OMA       423   

  dep_delayed_15min  
0                 N  
1                 N  
2                 N  
3                 N  
4                 Y

In [5]:
train["Month"] = [int(month[2:]) for month in train["Month"]]
train["DayofMonth"] = [int(day[2:]) for day in train["DayofMonth"]]
train['hour'] = train['DepTime'] // 100

train = train.drop("DepTime", axis=1)
train = train.drop("DayOfWeek", axis=1)

train["dep_delayed_15min"] = [1  if n == "Y" else 0 for n in train["dep_delayed_15min"]]

for col in ['Origin', 'Dest', 'UniqueCarrier']:
    train[col] = pd.factorize(train[col])[0]

print(test)

test["Month"] = [int(month[2:]) for month in test["Month"]]
test["DayofMonth"] = [int(day[2:]) for day in test["DayofMonth"]]
test['hour'] = test['DepTime'] // 100

test = test.drop("DepTime", axis=1)
test = test.drop("DayOfWeek", axis=1)
for col in ['Origin', 'Dest', 'UniqueCarrier']:
    test[col] = pd.factorize(test[col])[0]

      Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance
0       c-7       c-25       c-3      615            YV    MRY  PHX       598
1       c-4       c-17       c-2      739            WN    LAS  HOU      1235
2      c-12        c-2       c-7      651            MQ    GSP  ORD       577
3       c-3       c-25       c-7     1614            WN    BWI  MHT       377
4       c-6        c-6       c-3     1505            UA    ORD  STL       258
...     ...        ...       ...      ...           ...    ...  ...       ...
99995   c-6        c-5       c-2      852            WN    CRP  HOU       187
99996  c-11       c-24       c-6     1446            UA    ORD  LAS      1515
99997   c-1       c-30       c-2     1509            OO    ORD  SGF       438
99998   c-1        c-5       c-5      804            DL    LGA  ATL       761
99999  c-10       c-29       c-1      834            OO    MKE  MSP       297

[100000 rows x 8 columns]


In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Month              100000 non-null  int64
 1   DayofMonth         100000 non-null  int64
 2   UniqueCarrier      100000 non-null  int64
 3   Origin             100000 non-null  int64
 4   Dest               100000 non-null  int64
 5   Distance           100000 non-null  int64
 6   dep_delayed_15min  100000 non-null  int64
 7   hour               100000 non-null  int64
dtypes: int64(8)
memory usage: 6.1 MB


In [7]:
for column in train.columns:
    train[column] = (train[column] - train[column].min()) / (train[column].max() - train[column].min()) 
train.head()


Month  DayofMonth  UniqueCarrier    Origin      Dest  Distance  \
0  0.636364    0.666667       0.000000  0.000000  0.000000  0.142336   
1  0.272727    0.633333       0.047619  0.003472  0.003472  0.163017   
2  0.727273    0.033333       0.095238  0.006944  0.006944  0.078264   
3  0.909091    0.800000       0.142857  0.010417  0.010417  0.170722   
4  0.818182    0.200000       0.190476  0.013889  0.013889  0.079684   

   dep_delayed_15min  hour  
0                0.0  0.76  
1                0.0  0.60  
2                0.0  0.56  
3                0.0  0.40  
4                1.0  0.72

In [8]:
for column in test.columns:
    test[column] = (test[column] - test[column].min()) / (test[column].max() - test[column].min()) 
test.head()

Month  DayofMonth  UniqueCarrier    Origin      Dest  Distance      hour
0  0.545455    0.800000       0.000000  0.000000  0.000000  0.114987  0.250000
1  0.272727    0.533333       0.052632  0.003344  0.003367  0.244170  0.291667
2  1.000000    0.033333       0.105263  0.006689  0.006734  0.110728  0.250000
3  0.181818    0.800000       0.052632  0.010033  0.010101  0.070168  0.666667
4  0.454545    0.166667       0.157895  0.013378  0.013468  0.046035  0.625000

In [13]:
print(train['dep_delayed_15min'].value_counts())
df_class_0 = train[train['dep_delayed_15min'] == 0]
df_class_1 = train[train['dep_delayed_15min'] == 1]

0.0    80956
1.0    19044
Name: dep_delayed_15min, dtype: int64


In [14]:
df_class_0_over = df_class_0.sample(19044, replace=True)
train = pd.concat([df_class_0_over, df_class_1], axis=0)
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38088 entries, 55809 to 99993
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Month              38088 non-null  float64
 1   DayofMonth         38088 non-null  float64
 2   UniqueCarrier      38088 non-null  float64
 3   Origin             38088 non-null  float64
 4   Dest               38088 non-null  float64
 5   Distance           38088 non-null  float64
 6   dep_delayed_15min  38088 non-null  float64
 7   hour               38088 non-null  float64
dtypes: float64(8)
memory usage: 2.6 MB


In [15]:
x = train.drop(["dep_delayed_15min"], axis=1)
y = train["dep_delayed_15min"]

In [16]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.1,stratify=y)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(34279, 7)
(3809, 7)
(34279,)
(3809,)


In [21]:
from sklearn.svm import SVC
svc_s_model = SVC(kernel='rbf',gamma=8)
svc_s_model.fit(xtrain, ytrain)

SVC(gamma=8)

In [31]:
from xgboost import XGBClassifier
svc_model=XGBClassifier()
svc_model.fit(xtrain,ytrain)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
predictions= svc_s_model.predict(xtrain)
percentage=svc_s_model.score(xtrain,ytrain)
res=confusion_matrix(ytrain,predictions)
print("Training confusion matrix")
print(res)
predictions= svc_s_model.predict(xtest)
percentage=svc_s_model.score(xtest,ytest)
res=confusion_matrix(ytest,predictions)
print("validation confusion matrix")
print(res)
print(classification_report(ytest, predictions))
# check the accuracy on the training set
print('training accuracy = '+str(svc_s_model.score(xtrain, ytrain)*100))
print('testing accuracy = '+str(svc_s_model.score(xtest, ytest)*100))

Training confusion matrix
[[10757  6383]
 [ 4895 12244]]
validation confusion matrix
[[1169  735]
 [ 590 1315]]
              precision    recall  f1-score   support

         0.0       0.66      0.61      0.64      1904
         1.0       0.64      0.69      0.66      1905

    accuracy                           0.65      3809
   macro avg       0.65      0.65      0.65      3809
weighted avg       0.65      0.65      0.65      3809

training accuracy = 67.09939029726655
testing accuracy = 65.21396692045155


In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
predictions= svc_model.predict(xtrain)
percentage=svc_model.score(xtrain,ytrain)
res=confusion_matrix(ytrain,predictions)
print("Training confusion matrix")
print(res)
predictions= svc_model.predict(xtest)
percentage=svc_model.score(xtest,ytest)
res=confusion_matrix(ytest,predictions)
print("validation confusion matrix")
print(res)
print(classification_report(ytest, predictions))
# check the accuracy on the training set
print('training accuracy = '+str(svc_model.score(xtrain, ytrain)*100))
print('testing accuracy = '+str(svc_model.score(xtest, ytest)*100))

Training confusion matrix
[[12765  4375]
 [ 3696 13443]]
validation confusion matrix
[[1243  661]
 [ 608 1297]]
              precision    recall  f1-score   support

         0.0       0.67      0.65      0.66      1904
         1.0       0.66      0.68      0.67      1905

    accuracy                           0.67      3809
   macro avg       0.67      0.67      0.67      3809
weighted avg       0.67      0.67      0.67      3809

training accuracy = 76.45497243210129
testing accuracy = 66.68416907324757


In [26]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
dl_model = Sequential() 

dl_model.add(Dense(512,  activation = 'relu' ,input_shape=([7]))) #input layer
dl_model.add(Dense(512,  activation = 'relu'))
dl_model.add(Dense(1,activation = 'sigmoid'))
dl_model.summary()
dl_model.compile(optimizer = 'adam' , loss = 'binary_crossentropy' ,metrics = ['accuracy','Precision','Recall','AUC'])

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 512)               4096      
                                                                 
 dense_4 (Dense)             (None, 512)               262656    
                                                                 
 dense_5 (Dense)             (None, 1)                 513       
                                                                 
Total params: 267,265
Trainable params: 267,265
Non-trainable params: 0
_________________________________________________________________


In [29]:
num_epochs = 30
history = dl_model.fit(xtrain ,
                    ytrain ,
                    epochs= num_epochs ,
                    steps_per_epoch=50,
                    validation_data=(xtest ,ytest))

Epoch 1/30
50/50 [==============================] - 1s 20ms/step - loss: 0.6161 - accuracy: 0.6464 - precision: 0.6346 - recall: 0.6902 - auc: 0.7105 - val_loss: 0.6262 - val_accuracy: 0.6382 - val_precision: 0.6445 - val_recall: 0.6168 - val_auc: 0.6995
Epoch 2/30
50/50 [==============================] - 1s 20ms/step - loss: 0.6156 - accuracy: 0.6481 - precision: 0.6354 - recall: 0.6948 - auc: 0.7115 - val_loss: 0.6273 - val_accuracy: 0.6548 - val_precision: 0.6292 - val_recall: 0.7543 - val_auc: 0.7005
Epoch 3/30
50/50 [==============================] - 1s 21ms/step - loss: 0.6148 - accuracy: 0.6462 - precision: 0.6335 - recall: 0.6936 - auc: 0.7117 - val_loss: 0.6244 - val_accuracy: 0.6514 - val_precision: 0.6364 - val_recall: 0.7066 - val_auc: 0.7020
Epoch 4/30
50/50 [==============================] - 1s 21ms/step - loss: 0.6155 - accuracy: 0.6490 - precision: 0.6362 - recall: 0.6958 - auc: 0.7110 - val_loss: 0.6245 - val_accuracy: 0.6472 - val_precision: 0.6413 - val_recall: 0.668

In [30]:
dl_model.evaluate(xtest,ytest)

120/120 [==============================] - 1s 4ms/step - loss: 0.6243 - accuracy: 0.6414 - precision: 0.6428 - recall: 0.6367 - auc: 0.7022


[0.6242818236351013,
 0.6413756608963013,
 0.6428192853927612,
 0.6367453932762146,
 0.7022359371185303]

In [34]:
sub = pd.read_csv(r"C:\Users\sairam\Downloads\flight-delays-fall-2018\sample_submission.csv")
target=dl_model.predict(test)
sub['dep_delayed_15min']=target
sub.to_csv('flight delay prediction comp-3.csv', index=False)

3125/3125 [==============================] - 11s 3ms/step
